name: Run Integrations Tests

permissions: 
  checks: write
  contents: read

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
  schedule:
    # M-F at 06:17 GMT
    - cron: '17 6 * * 1-5'

env:
  DD_DESTINATION_API_KEY: ${{ secrets.DD_DESTINATION_API_KEY }}
  DD_DESTINATION_APP_KEY: ${{ secrets.DD_DESTINATION_APP_KEY }}
  DD_DESTINATION_API_URL: ${{ secrets.DD_DESTINATION_API_URL }}
  DD_SOURCE_API_KEY: ${{ secrets.DD_SOURCE_API_KEY }}
  DD_SOURCE_APP_KEY: ${{ secrets.DD_SOURCE_APP_KEY }}
  DD_SOURCE_API_URL: ${{ secrets.DD_SOURCE_API_URL }}
  DD_HTTP_CLIENT_RETRY_TIMEOUT: 300

jobs:
  test-integrations:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"
    steps:
      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.12
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run integration tests
        run: tox -e integration
        env:
          DD_AGENT_HOST: localhost
          DD_ENV: ci
          DD_SERVICE: datadog-sync-cli
          DD_TAGS: "team:hamr"
          DD_TRACE_ANALYTICS_ENABLED: "true"
          RECORD: "none"
          PYTEST_ADDOPTS: "--ddtrace --disable-recording --retries 2"
